CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -39,8 +39,6 @@ jobs:
     name: Docker Build & Push
     runs-on: ubuntu-latest
     needs: build-and-test
-    env:
-      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/cleanmap-api
 
     steps:
       - name: Checkout code
@@ -48,6 +46,14 @@ jobs:
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
+
+      - name: Set image name
+        run: |
+          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
+            echo "DOCKER_USERNAME secret is missing." >&2
+            exit 1
+          fi
+          echo "IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/cleanmap-api" >> $GITHUB_ENV
 
       - name: Log in to Docker Hub
         if: github.event_name == 'push'
